'use client'
import { useSyncExternalStore } from 'react'
import { usePathname } from 'next/navigation'

/* The current path, but only once the browser is driving.
 *
 * ── The bug this exists to prevent ───────────────────────────────────────────────────────
 *
 * The homepage threw React #418 — "hydration failed because the server rendered HTML didn't
 * match the client" — on every clean load in Production, and the cause was the navigation's
 * own active marker.
 *
 * `usePathname()` returns the route during a local build, so `.next/server/app/index.html`
 * carried the active underline for Home. Production's served HTML carried **zero** active
 * markers. On Vercel these pages are regenerated by ISR (`export const revalidate = 3600`),
 * and in that render the hook does not resolve to the route — so the server produced a nav
 * with no marker while the browser, one tick later, produced a nav with one. React found an
 * element in the client tree that was not in the server HTML and threw the whole subtree
 * away to re-render it.
 *
 * That is why the local build was clean and Production was not: it is not a code path that
 * differs, it is a *render environment* that differs. Testing the build output would never
 * have caught it.
 *
 * ── Why this shape ───────────────────────────────────────────────────────────────────────
 *
 * Not `suppressHydrationWarning`: the mismatch is entirely avoidable, and suppressing it
 * would leave React quietly discarding and re-rendering the header on every page load.
 *
 * Not "always render the marker and hide it with a class" either: that keeps the element
 * tree stable but moves the divergence into an attribute, which is the same bug wearing a
 * smaller hat.
 *
 * Instead the first render is made *identical by construction*. `getServerSnapshot` returns
 * false, so the hydrating render sees no path and marks nothing active — exactly what the
 * server sent, whichever way the server rendered it. Immediately after hydration React reads
 * `getSnapshot`, sees `true`, and re-renders with the real path. The marker appears a frame
 * late and is correct from then on, including across client-side navigation.
 *
 * The cost is that frame. The alternative is a header React rebuilds from scratch on every
 * load, and an error in every visitor's console.
 *
 * This is the same pattern `MemberNavLink` uses to read its cookie, deliberately: there is
 * one way in this codebase to say "this value only exists in the browser". */

/* No subscription: hydration happens once and never un-happens. */
const subscribe = () => () => {}
const hydrated = () => true
const notYet = () => false

/** The current pathname once hydrated, and `null` during server render and the hydrating
 *  render. Callers must treat `null` as "no route is active yet" rather than as an error —
 *  that is the whole point, and it is why this returns `null` instead of `''`. */
export function useCurrentPath(): string | null {
  const pathname = usePathname()
  return useSyncExternalStore(subscribe, hydrated, notYet) ? pathname : null
}

/** Whether `href` is the active route, given a possibly-absent path.
 *
 *  Exported and pure so the rule can be tested without a browser, and shared so the desktop
 *  header and the bottom navigation cannot drift apart about what "active" means. */
export function isActivePath(
  pathname: string | null, href: string, exact: boolean,
): boolean {
  if (!pathname) return false
  if (exact) return pathname === href
  /* "/" is a prefix of every route, so a non-exact Home entry would light up everywhere. */
  return href !== '/' && pathname.startsWith(href)
}
