import { describe, it, expect } from 'vitest'
import { isActivePath } from './useCurrentPath'
import { readFileSync } from 'node:fs'

/* React #418 on every clean load of the homepage in Production.
 *
 * The navigation's active marker is an extra element in the tree — an underline span in the
 * header, a dot in the bottom bar. `usePathname()` resolved to the route when the page was
 * built locally, so `.next/server/app/index.html` carried the marker; Production's served
 * HTML carried none, because those pages are regenerated by ISR and the hook does not
 * resolve the same way in that render. Server said "nothing active", the browser said "Home
 * is active", and React threw the subtree away.
 *
 * The tests below hold both halves of the fix: the rule is pure and shared, and no
 * navigation component decides "active" from a path it cannot have yet. */

describe('what counts as the active route', () => {
  it('marks nothing active when there is no path yet', () => {
    /* The whole point. During server render and the hydrating render the path is null, and
       null must mean "not active" rather than throwing or guessing. */
    for (const href of ['/', '/palace', '/gallery']) {
      expect(isActivePath(null, href, true)).toBe(false)
      expect(isActivePath(null, href, false)).toBe(false)
    }
  })

  it('matches an exact entry only on itself', () => {
    expect(isActivePath('/', '/', true)).toBe(true)
    expect(isActivePath('/palace', '/', true)).toBe(false)
    expect(isActivePath('/palace/the-coronation', '/palace', true)).toBe(false)
  })

  it('matches a section entry on its own pages', () => {
    expect(isActivePath('/palace', '/palace', false)).toBe(true)
    expect(isActivePath('/palace/the-coronation', '/palace', false)).toBe(true)
    expect(isActivePath('/gallery', '/palace', false)).toBe(false)
  })

  it('never lets a non-exact Home entry light up everywhere', () => {
    /* "/" is a prefix of every route. Without the guard, a Home tab marked non-exact would
       be active on all 231 pages. */
    for (const p of ['/', '/palace', '/gallery/images', '/quarters/fun']) {
      expect(isActivePath(p, '/', false)).toBe(false)
    }
  })

  it('is never fooled by a prefix that is not a path segment', () => {
    expect(isActivePath('/gallery', '/gal', false)).toBe(true)
    /* Documented rather than asserted as desirable: the rule is a plain prefix match, which
       is what the navigation has always done and what its entries are written for. No
       current entry is a prefix of another. */
  })
})

describe('no navigation component decides active from a path it cannot have', () => {
  const strip = (s: string) =>
    s.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/\/\/[^\n]*/g, ' ')

  const NAVS = ['src/components/layout/Header.tsx', 'src/components/layout/MobileNav.tsx']

  it('reads the path through the hydration-safe hook, not usePathname', () => {
    for (const f of NAVS) {
      const code = strip(readFileSync(f, 'utf-8'))
      expect(code).toContain('useCurrentPath')
      expect(code).not.toContain('usePathname')
    }
  })

  it('decides active through the shared rule rather than its own comparison', () => {
    for (const f of NAVS) {
      const code = strip(readFileSync(f, 'utf-8'))
      expect(code).toContain('isActivePath(')
      /* The two hand-rolled comparisons that drifted apart and both broke hydration. */
      expect(code).not.toMatch(/pathname\s*===\s*\w+\.href/)
      expect(code).not.toMatch(/pathname\.startsWith\(/)
    }
  })

  it('uses the server snapshot pattern rather than suppressing the warning', () => {
    /* `suppressHydrationWarning` would silence the error and leave React rebuilding the
       header on every page load. The mismatch is avoidable, so it is avoided. */
    const hook = readFileSync('src/components/layout/useCurrentPath.ts', 'utf-8')
    expect(hook).toContain('useSyncExternalStore')
    /* Comments stripped: the hook explains at length why it does *not* suppress the warning,
       and matching that prose would fail on the reasoning itself. */
    for (const f of [...NAVS, 'src/components/layout/useCurrentPath.ts']) {
      expect(strip(readFileSync(f, 'utf-8'))).not.toContain('suppressHydrationWarning')
    }
  })
})
